/// A row of `zad_transactions`, and the rules the table enforces.
///
/// The CHECK constraints are mirrored here as constructors rather than as
/// validation, so an invalid combination cannot be built in the first place.
/// That is not tidiness: a row the server refuses becomes a dead letter in the
/// outbox, and a dead letter is a write the user was told had saved. The place
/// to catch it is before it is queued.
library;

import 'package:zad/core/money/money.dart';

/// `zad_transactions.txn_kind`.
enum TxnKind {
  /// Money out.
  expense('expense'),

  /// Money in.
  income('income'),

  /// Money moved between the user's own wallets.
  transfer('transfer');

  new(this.wireName);

  /// The value stored in the column.
  final String wireName;

  /// Reads the column, defaulting to [expense] as the table's own default does.
  static TxnKind fromWire(String? value) => values.firstWhere(
    (k) => k.wireName == value,
    orElse: () => TxnKind.expense,
  );
}

/// `zad_transactions.wallet` and `transfer_to`.
enum Wallet {
  /// Physical cash.
  cash('cash'),

  /// A card.
  card('card'),

  /// A bank account.
  bank('bank');

  new(this.wireName);

  /// The value stored in the column.
  final String wireName;

  /// Reads the column, defaulting to [card] as the table's own default does.
  static Wallet fromWire(String? value) =>
      values.firstWhere((w) => w.wireName == value, orElse: () => Wallet.card);
}

/// One transaction.
class ZadTransaction {
  const new _({
    required this.id,
    required this.userId,
    required this.amount,
    required this.title,
    required this.createdAt,
    required this.wallet,
    required this.kind,
    required this.isExpense,
    this.category,
    this.transferTo,
    this.currency,
    this.countsTowardBudget = true,
    this.merchantName,
    this.isPending = false,
  });

  /// Money out.
  ///
  /// [id] is generated by the caller before the row is written anywhere, so the
  /// local cache, the outbox entry and the server row all share it.
  factory expense({
    required String id,
    required String userId,
    required double amount,
    required String title,
    required DateTime createdAt,
    required Wallet wallet,
    String? category,
    String? currency,
    String? merchantName,
    bool countsTowardBudget = true,
    bool isPending = false,
  }) => ZadTransaction._(
    id: id,
    userId: userId,
    amount: amount.asMoney,
    title: title,
    createdAt: createdAt,
    wallet: wallet,
    kind: TxnKind.expense,
    isExpense: true,
    category: category,
    currency: currency,
    merchantName: merchantName,
    countsTowardBudget: countsTowardBudget,
    isPending: isPending,
  );

  /// Money in.
  factory income({
    required String id,
    required String userId,
    required double amount,
    required String title,
    required DateTime createdAt,
    required Wallet wallet,
    String? category,
    String? currency,
    bool isPending = false,
  }) => ZadTransaction._(
    id: id,
    userId: userId,
    amount: amount.asMoney,
    title: title,
    createdAt: createdAt,
    wallet: wallet,
    kind: TxnKind.income,
    isExpense: false,
    category: category,
    currency: currency,
    isPending: isPending,
  );

  /// Money moved between the user's own wallets.
  ///
  /// [to] is required and cannot equal [from]. The table's
  /// `transfer_needs_target` CHECK covers the first half; the second is this
  /// app's rule, since a transfer to the wallet it came from is a no-op that
  /// would still fire the notification triggers.
  factory transfer({
    required String id,
    required String userId,
    required double amount,
    required String title,
    required DateTime createdAt,
    required Wallet from,
    required Wallet to,
    String? currency,
    bool isPending = false,
  }) {
    if (from == to) {
      throw ArgumentError.value(
        to.wireName,
        'to',
        'a transfer must move money between different wallets',
      );
    }
    return ZadTransaction._(
      id: id,
      userId: userId,
      amount: amount.asMoney,
      title: title,
      createdAt: createdAt,
      wallet: from,
      kind: TxnKind.transfer,
      isExpense: false,
      transferTo: to,
      currency: currency,
      // A transfer moves money, it does not spend it.
      countsTowardBudget: false,
      isPending: isPending,
    );
  }

  /// Reads a row the server sent.
  ///
  /// The server is trusted here: its BEFORE INSERT triggers have already
  /// reconciled `txn_kind` against `is_expense` and converted the amount into
  /// the account's currency, so whatever arrives is authoritative even where it
  /// differs from what this client sent.
  factory fromJson(Map<String, dynamic> json) => ZadTransaction._(
    id: json['id'] as String,
    userId: json['user_id'] as String,
    amount: (json['amount'] as num).toDouble(),
    title: json['title'] as String,
    createdAt: DateTime.parse(json['created_at'] as String).toUtc(),
    wallet: Wallet.fromWire(json['wallet'] as String?),
    kind: TxnKind.fromWire(json['txn_kind'] as String?),
    isExpense: json['is_expense'] as bool? ?? true,
    category: json['category'] as String?,
    transferTo: switch (json['transfer_to']) {
      final String w => Wallet.fromWire(w),
      _ => null,
    },
    currency: json['currency'] as String?,
    countsTowardBudget: json['counts_toward_budget'] as bool? ?? true,
    merchantName: json['merchant_name'] as String?,
    isPending: json['_pending'] as bool? ?? false,
  );

  /// The row id, decided on the device.
  final String id;

  /// Whose row this is. RLS requires it to equal `auth.uid()`.
  final String userId;

  /// The amount, always positive; direction lives in [isExpense].
  ///
  /// This is what the **server** stored once [isPending] is false. While the
  /// row is pending it is what this device sent, which can still change:
  /// `zad_normalize_transaction_currency` converts a foreign-currency amount
  /// into the account's own and moves the original into `original_amount`. The
  /// client cannot do that conversion itself — the rates live in `zad_fx_rates`
  /// — so a pending foreign-currency amount is an estimate.
  final double amount;

  /// What the user called it.
  final String title;

  /// When it happened.
  final DateTime createdAt;

  /// Where the money came from.
  final Wallet wallet;

  /// Expense, income or transfer.
  final TxnKind kind;

  /// Whether this is money out.
  final bool isExpense;

  /// The spending category. Stays in Arabic: it is matched and stored, not
  /// displayed from a translation table.
  final String? category;

  /// For a transfer, where the money went.
  final Wallet? transferTo;

  /// The amount's currency, or null meaning the account's own.
  final String? currency;

  /// Whether this counts against the budget.
  final bool countsTowardBudget;

  /// The merchant, when a bank message named one.
  final String? merchantName;

  /// Whether this row is still only local.
  ///
  /// Not a column. It is kept in the cache so the UI can mark the row as not
  /// yet confirmed, and it is stripped from what is sent.
  final bool isPending;

  /// The body to insert, in the server's column names.
  ///
  /// `id` is included on purpose: it is what makes a replay collide instead of
  /// duplicating. Columns the server owns — `original_amount`,
  /// `original_currency`, `is_verified` — are left out.
  Map<String, dynamic> toInsertJson() => <String, dynamic>{
    'id': id,
    'user_id': userId,
    'amount': amount,
    'title': title,
    'category': category,
    'is_expense': isExpense,
    'created_at': createdAt.toUtc().toIso8601String(),
    'wallet': wallet.wireName,
    'txn_kind': kind.wireName,
    'transfer_to': transferTo?.wireName,
    'currency': currency,
    'counts_toward_budget': countsTowardBudget,
    'merchant_name': merchantName,
  };

  /// The form kept in the local cache, which is the insert body plus the local
  /// pending flag.
  Map<String, dynamic> toCacheJson() => <String, dynamic>{
    ...toInsertJson(),
    '_pending': isPending,
  };

  /// Returns a copy with [isPending] set.
  ZadTransaction markPending({required bool pending}) => ZadTransaction._(
    id: id,
    userId: userId,
    amount: amount,
    title: title,
    createdAt: createdAt,
    wallet: wallet,
    kind: kind,
    isExpense: isExpense,
    category: category,
    transferTo: transferTo,
    currency: currency,
    countsTowardBudget: countsTowardBudget,
    merchantName: merchantName,
    isPending: pending,
  );
}
