name: Build Flutter Debug APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
        working-directory: zad_flutter
      - run: flutter build apk --debug
        working-directory: zad_flutter
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: zad_flutter/build/app/outputs/flutter-apk/app-debug.apk
